name: Dev Release
on: [workflow_dispatch]
jobs:
  dev-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Create a file
        run: echo "123" > my_file.txt
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: ${{ github.workspace }}
